openflexure_labelling_tool_app/slides/__init__.py
from flask import Blueprint

bp = Blueprint("slides", __name__)

from openflexure_labelling_tool_app.slides import routes

openflexure_labelling_tool_app/slides/routes.py
import json
import logging
from datetime import datetime
from pathlib import Path

from flask import (
    abort,
    current_app,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    safe_join,
    send_file,
    send_from_directory,
    url_for,
)
from flask_login import current_user, login_required
from sqlalchemy.sql.expression import func

from openflexure_labelling_tool_app import db
from openflexure_labelling_tool_app.models import (
    Image,
    Label,
    LabellingSession,
    User,
    ZMove,
    ZStack,
)
from openflexure_labelling_tool_app.slides import bp


@bp.route("/", methods=["GET"])
@login_required
def slides():
    # get last labelling session that hasn't been completed
    labelling_session = (
        LabellingSession.query.filter_by(user_id=current_user.id)
        .filter_by(is_completed=False)
        .order_by(LabellingSession.timestamp)
        .first()
    )
    # create new labelling session from user, and next in list of images
    if labelling_session is None:
        z_stack = get_next_z_stack(current_user)
        if z_stack is None:
            flash("There are no more slides for you to label!", "success")
            return redirect(url_for("main.index"))
        labelling_session = LabellingSession(
            z_stack_id=z_stack.id, user_id=current_user.id, is_completed=False
        )
        db.session.add(labelling_session)
        db.session.commit()
    labelling_session.time_stamp = datetime.utcnow()
    db.session.commit()
    return render_template(
        "slides/slides.html",
        title="Label slides",
        labels=labelling_session.labels.filter_by(is_deleted=False).all(),
        zStack=labelling_session.z_stack,
        images=labelling_session.z_stack.images.order_by(Image.slide_z.asc()).all(),
        labelling_session=labelling_session,
        slides_folder=current_app.config["SLIDES_FOLDER"],
        default_label_options=current_app.config["LABEL_OPTIONS"],
    )


@bp.route("/img/<int:id>", methods=["GET"])
@login_required
def get_img(id):
    image = Image.query.get_or_404(id)
    if not image.check_hash():
        return abort(404)
    return send_from_directory(current_app.config["SLIDES_FOLDER"], image.file_location)


@bp.route("/save-label", methods=["POST"])
@login_required
def save_label():
    label_id = request.form["label_id"]
    ask_question = json.loads(request.form["ask_question"])
    labelling_session_id = int(request.form["labelling_session_id"])
    shape = request.form["shape"]
    image_x = int(request.form["image_x"])
    image_y = int(request.form["image_y"])
    image_delta_x = int(request.form["image_delta_x"])
    image_delta_y = int(request.form["image_delta_y"])
    label_type = request.form["label_type"]
    image_id = int(request.form["image_id"])
    label_options = request.form["label_options"].split(",")
    if ask_question == False:
        label = Label(
            image_id=image_id,
            labelling_session_id=labelling_session_id,
            user_id=current_user.id,
            shape=shape,
            image_x=image_x,
            image_y=image_y,
            image_delta_x=image_delta_x,
            image_delta_y=image_delta_y,
            label_type=label_type,
            label_options=label_options,
            is_deleted=False,
            timestamp=datetime.utcnow(),
        )
        labelling_session = LabellingSession.query.get(labelling_session_id)
        labelling_session.labels.append(label)
    else:
        label = Label.query.get(label_id)
        label.label_type = label_type
        label.timestamp = datetime.utcnow()
    db.session.commit()
    return str(label.id)


@bp.route("/save-z-move", methods=["POST"])
@login_required
def save_z_move():
    image_id = int(request.form["image_id"])
    labelling_session_id = int(request.form["labelling_session_id"])
    is_move_up = request.form["is_move_up"] == "true"
    z_move = ZMove(
        image_id=image_id,
        labelling_session_id=labelling_session_id,
        is_move_up=is_move_up,
        timestamp=datetime.utcnow(),
        user_id=current_user.id,
    )
    db.session.add(z_move)
    db.session.commit()
    return jsonify({"message": "z move saved"})


@bp.route("/save-labelling-session", methods=["POST"])
@login_required
def save_labelling_session():
    labelling_session_id = int(request.form["labelling_session_id"])
    is_completed = json.loads(request.form["is_completed"])
    labelling_session = LabellingSession.query.get(int(labelling_session_id))
    if current_user.id == labelling_session.user_id:
        labelling_session.time_taken = (
            labelling_session.time_taken
            + datetime.utcnow()
            - labelling_session.timestamp
        )
        labelling_session.is_completed = is_completed
        db.session.commit()
    return jsonify({"message": "labelling session saved"})


@bp.route("/delete-label", methods=["POST"])
@login_required
def delete_label():
    label_id = int(request.form["label_id"])
    label = Label.query.get(label_id)
    labelling_session_id = int(request.form["labelling_session_id"])
    if label.labelling_session_id == labelling_session_id:
        if label.user_id == current_user.id or current_user.is_admin:
            label.is_deleted = True
            db.session.commit()
            return jsonify({"message": "label deleted"})
        else:
            return jsonify({"message": "You do not have permission to do that"}), 403
    else:
        return jsonify({"message": "Bad request"}), 400


def get_next_z_stack(current_user):
    # get the first zstack where there are no labelling sessions by the current user.
    z_stacks = (
        ZStack.query.filter_by(is_active=True)
        .outerjoin(ZStack.labelling_sessions)
        .group_by(ZStack.id)
        .order_by(func.count(LabellingSession.id).asc())
        .all()
    )
    for z_stack in z_stacks:
        if (
            z_stack.labelling_sessions.filter(
                LabellingSession.user_id == current_user.id
            ).count()
            == 0
        ):
            return z_stack
    return None

openflexure_labelling_tool_app/templates/slides/slides.html
{% extends "base.html" %}
{% set active_page = "slide" %}
{% set show_nav_bar = false %}
{% block head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/4.0.0-beta.12/fabric.min.js"></script>
<script src="{{ url_for('static',filename='app.js') }}"></script>


{% endblock %}
{% block content %}
<script>
	let labelling_session_saved =false
	var csrf_token = "{{ csrf_token() }}";

		$.ajaxSetup({
			beforeSend: function (xhr, settings) {
				if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
					xhr.setRequestHeader("X-CSRFToken", csrf_token);
				}
			}
		});

    window.addEventListener('beforeunload', (event) => {
		if (!labelling_session_saved){
			var url = "{{url_for('slides.save_labelling_session')}}";
			var data = {labelling_session_id: {{labelling_session.id}}, is_completed: false}
			$.post(url, data)
		}
    });

</script>
<div style="width:1152px; margin:0 auto;">
		<canvas id="canvas" width="1152" height="720" style="border: 2px solid black"></canvas>
</div>
<div class="uk-container uk-container-small uk-flex uk-flex-center">
		<progress id="zStackProgress" class="uk-progress" value="" max=""></progress>
</div>
	<div class="uk-button-group uk-margin-small uk-flex uk-flex-center">
		<button id="btnMoveDownZ" class="uk-button uk-button-primary" uk-icon="icon: triangle-down; ratio: 2"
			onclick="moveDownZ()">Move down Z</button>
		<button id="btnFinishedLabelling" class="uk-button uk-button-danger" onclick="saveLabellingSession()">Loading images... <div uk-spinner></div></button>
		<button id="btnMoveUpZ" class="uk-button uk-button-primary" uk-icon="icon:triangle-up; ratio: 2"
			onclick="moveUpZ()">Move up Z</button>
	</div>
</div>
<div id="labelTypeModal" uk-modal="esc-close: false; bg-close: false;">
	<div class="uk-modal-dialog">
		<div class="uk-modal-body uk-text-center">
			<div id="labelTypeModalRadio" class="uk-form-control">
			</div>
		</div>
		<div class="uk-modal-footer uk-text-center">
			<button id="btn_delete_label" class="uk-button uk-button-danger" type="button">Delete label</button>
			<button id="btn_save_label" class="uk-button uk-button-primary" type="button">Save
				label</button>

		</div>
	</div>
</div>
<script>
	let defaultLabelOptions;
	let zNumber;
	let zStack = new Array();
	let imageIDs = new Array();
	let scale_x;
	let scale_y;
	function preloadSlideTiles() {
		{% for image in images %}
			zStack[{{loop.index0}}] = new Image();
			zStack[{{loop.index0}}].src = "{{ url_for('slides.get_img',id = image.id) }}";
			imageIDs[{{loop.index0}}] = {{image.id}};
		{% endfor %}
	};
	function saveZMove(is_move_up){
		var url = "{{ url_for('slides.save_z_move')}}";
		$.post(url, {image_id:imageIDs[zNumber], labelling_session_id: {{labelling_session.id}}, is_move_up  : is_move_up});
	};

	function checkAllLabelled(value, index, array){
		return typeof value.labelType !== "undefined"
	};

	function saveLabellingSession(){
		//Mark labelling session as complete

		if (fabricCanvas._objects.every(checkAllLabelled)){
			var url = "{{url_for('slides.save_labelling_session')}}";
			$.post(url, {labelling_session_id: {{labelling_session.id}}, is_completed: true}).done(function (response){
				console.log(response['message'])
				labelling_session_saved=true
				UIkit.modal.confirm('Labelling session saved. Would you like to label another slide?', {labels:{ok: 'Next slide', cancel: 'Exit labelling'}}).then(function(){
				window.location.replace("{{url_for('slides.slides')}}");
				}, function(){
					window.location.replace("{{url_for('main.index')}}");
				});
			});
		} else {
			UIkit.modal.alert('Not all the labels have been given a type.  Please click on the yellow labels and assign them a type.')
		}

	};

	function loadLabels(){
		{% for label in labels %}
		rect = new fabric.Rect({
			left : {{label.image_x}} / scale,
			top  : {{label.image_y}} / scale,
			width: {{label.image_delta_x}}/scale,
			height : {{label.image_delta_y}}/scale,
			{% if label.ask_question == true%}
			askQuestion: true,
			question: "{{label.question}}",
			labelOptions : {{label.label_options| safe}},
			...options.newRectProps,
			{% else %}
			labelType: "{{label.label_type}}",
			labelOptions : defaultLabelOptions,
			...options.savedRectProps,
			{% endif %}
		});
		rect.id = {{label.id}}
		fabricCanvas.add(rect);
		rect.dirty = true;
		{% endfor %}
		fabricCanvas.renderAll();
	};

	preloadSlideTiles();


	$('#btn_delete_label').click(function (e) {
		$('#labelTypeModalRadio').html("<div uk-spinner></div>");
		selectedLabel = fabricCanvas.getActiveObject();
		if (typeof selectedLabel.id !== 'undefined') {
			var url = "{{ url_for('slides.delete_label') }}";
			$.post(url, {label_id: selectedLabel.id, labelling_session_id: {{labelling_session.id}}
			}).done(function (response) {
				console.log(response['message'])
			}).fail(function () {
				console.log("Error, could not contact server.")
			});
		}
		fabricCanvas.remove(selectedLabel);
		fabricCanvas.requestRenderAll();
		UIkit.modal(labelTypeModal).hide();
	});

	$('#btn_save_label').click(function (e) {
		var url = "{{ url_for('slides.save_label') }}";
		selectedLabel = fabricCanvas.getActiveObject();
		var typeRadioElements = document.getElementsByName("typeRadio");
		for (i = 0; i < typeRadioElements.length; i++) {
			if (typeRadioElements[i].checked) {
				selectedLabel.labelType = typeRadioElements[i].value;
			}
		}
		if (typeof selectedLabel.id === 'undefined') {
			selectedLabel.id = null
		}
		$('#labelTypeModalRadio').html("<div uk-spinner></div>");
		var shape = "rect";
		var image_x = Math.round(selectedLabel.left*scale);
		var image_y = Math.round(selectedLabel.top*scale);
		var image_delta_x = Math.round(selectedLabel.width*scale);
		var image_delta_y = Math.round(selectedLabel.height*scale);
		var label_type = selectedLabel.labelType;
		var ask_question = selectedLabel.askQuestion;
		var image_id = imageIDs[zNumber];
		var label_options = selectedLabel.labelOptions.toString();
	$.post(url, {label_id: selectedLabel.id, labelling_session_id: {{labelling_session.id}}, ask_question:ask_question,shape: shape, image_x: image_x, image_y: image_y, image_delta_x: image_delta_x, image_delta_y: image_delta_y, label_type: label_type, label_options: label_options, image_id: image_id}).done(function (response) {
		selectedLabel.id = parseInt(response);
		selectedLabel.stroke = 'red';
		selectedLabel.dirty = true;
		fabricCanvas.renderAll();
		UIkit.modal(labelTypeModal).hide();
	}).fail(function () {
		console.log("Error, could not contact server.")
	})
	});


	slideLabel = document.getElementById("slideLabel");
	btnMoveUpZ = document.getElementById("btnMoveUpZ");
	btnMoveDownZ = document.getElementById("btnMoveDownZ");
	
	defaultLabelOptions = {{default_label_options | safe}};
	
	zNumber = Math.floor(zStack.length / 2);
	document.getElementById('zStackProgress').max = zStack.length - 1;
	zStack[zNumber].onload = function (){
		console.log("loading canvas");
		canvas = document.getElementById('canvas');
		fabricCanvas = new fabric.Canvas(canvas);
		scale = zStack[0].width/canvas.width;
		fabricCanvas.setHeight(zStack[0].height/scale);
		fabricCanvas.calcOffset();
		loadLabels();
		
		
		fabricCanvas.selection = false;
		fabricCanvas.on('mouse:down', onMouseDown);
		fabricCanvas.on('mouse:move', onMouseMove);
		fabricCanvas.on('mouse:up', onMouseUp);
		fabricCanvas.on('mouse:wheel', function (opt) {
			if (opt.e.deltaY < 0) {
				moveUpZ();
			} else {
				moveDownZ();
			}
			});
		showNewImage();
		$('#btnFinishedLabelling').html("Finished labelling")
	};	

	rect = null



</script>
{% endblock %}